server:
  port: 8423

armagin:
  kafka:
    ip: localhost
    port: 9092
  snowflake:
    worker:
      id: 1
    data:
      center:
        id: 1

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: armagin-user
  # 配置Kafka
  kafka:
    bootstrap-servers: ${armagin.kafka.ip}:${armagin.kafka.port}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 128kb
      batch-size: 131072
      # 64M
      buffer-memory: 67108864
      # max-request-size: 5242880
      # linger-ms: 5
      retries: 1
      acks: 0
      # 提升性能很重要
      compression-type: gzip
      properties:
        # 5M
        max.request.size: 5242880
        linger.ms: 5
    consumer:
      -auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 3000

  # 配置Redis
  redis:
    host: localhost
    port: 6379
  # 数据库配置
  datasource:
    #druid配置
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/armagin?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

#配置mybatis
mybatis:
  #映射文件所在的位置
  mapper-locations: classpath*:mapper/**/*.xml
  #开启驼峰功能
  configuration:
    map-underscore-to-camel-case: true

#sa-token配置
sa-token:
  token-name: armagin-token
  # 7天
  timeout: 604800
  # (指定时间内无操作就视为token过期) 单位: 秒，-1表示永不过期
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  token-session-check-login: false
  is-share: false
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  is-read-head: true
  # 自动续签
  auto-renew: true